version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword123
    volumes:
      - timescale-data:/var/lib/postgresql/data

  
volumes:
  timescale-data: